//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSet2ExcelDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tab_analysis_type
    {
        public int id { get; set; }
        public string analysis_category { get; set; }
        public string analysis_name { get; set; }
        public Nullable<int> analysis_fun { get; set; }
        public Nullable<int> exam_type { get; set; }
        public string use_joints { get; set; }
        public Nullable<int> ptr_order { get; set; }
        public Nullable<int> result_num { get; set; }
        public string reference_analysis_type { get; set; }
    }
}
